### PR TITLE
Add option to not open email client

### PR DESCRIPTION
**Pull request by statsmaths**
As discussed on slack, there was a desire to create an email template without actually trying to open an email client. If there is a better approach to this, feel free to decline and do this another way.

### CODE REVIEW

**Comment by s-u** [comment]
IMHO this is the wrong approach. I would argue that it would make a lot more sense to govern what happens when an e-mail is generated in `rj`. One option is to open an e-mail client, but it's easy to just change it to opening a text editor instead or just copy it into a pasteboard... but do it consistently for all communications, not just `add_reviewer`

**Comment by s-u** [comment]
I'll look into modifying `email_text` or similar as an alternative... but please comment what would you prefer as the possible actions - so far I was thinking of:
- open mailto: URL
- open editor
- copy to pasteboard

any others?

**Comment by statsmaths** [comment]
Sure, that's fine with me. That's why I even said that I wasn't sure this was actually the best approach (I really don't understand the whole package, just the few small parts I use). FWIW, copying to the clipboard with clipr or similar would be ideal for me.

**Comment by statsmaths** [comment]
Thanks Simon; just didn't want to add a feature request without at least trying to offer a (likely misguided) approach. I'll close this and just use my fork locally until there's a better global solution.

**Comment by markvanderloo** [comment]
Opening in an editor or just printing to screen would be great. I now had no option but to lower the security settings on my email account in order to connect with my system's mail client. I'm sure there are safer options but I'm not all that knowledgeable in these matters. Neither on security nor on mail protocols. I basically push ok untill it works, which makes me uneasy. Also because I haven't the faintest idea on how to reinstate the security settings.  

I also tend to keep my OS close to vanilla as any adjustments I make now I need to repeat when I upgrade hardware. 

I know this is just a matter of taste but in any case, if any of these options could be included that would be great :-).

**Comment by s-u** [comment]
@markvanderloo @statsmaths I have added `RJ_EMAIL_TOOL` env var option - see https://github.com/rjournal/rj/blob/master/NEWS.md for details. I did only basic testing on macOS, so let me know if you find issues.

**Comment by markvanderloo** [comment]
Thanks for this effort Simon! I still get no joy when I set `RJ_EMAIL_TOOL` to `"edit"`. I may have a look at the code later to see where it's coming from. (working on an Ubuntu 20.04 box)

**Pull request closed without merging**
