### PR TITLE
Simplified installation process by adding remotes to DESCRIPTION

### PR DESCRIPTION
**Pull request by mitchelloharawild**

### CODE REVIEW

**Comment by dicook** [comment]
Changes done manually

**Comment by mitchelloharawild** [comment]
Any reason for not specifying jss as a `Remote` if the package is installed via `remotes::install_github()`?

**Comment by csgillespie** [comment]
I don't think so. I've added jss to the GH action to install via the repo, but your way is probably cleaner

**Comment by csgillespie** [comment]
If we specify jss as a remote, then just close #11 . 

@dicook Did you mean to omit the svn remote?

**Pull request closed without merging**
