### PR TITLE
Load editors list from file

### PR DESCRIPTION
**Pull request by mitchelloharawild**
cc @dicook

### CODE REVIEW

**Comment by mitchelloharawild** [comment]
An `editors.txt` file needs to be added to the articles repo.
The contents of the file should be:

```
Hadley Wickham <h.wickham@gmail.com>, 
Heather Turner <ht@heatherturner.net>, 
Martyn Plummer <Martyn.Plummer@r-project.org>, 
Deepayan Sarkar <deepayan.sarkar@r-project.org>, 
Bettina Grün <Bettina.Gruen@jku.at>, 
Michael Lawrence <lawrence.michael@gene.com>, 
Roger Bivand <Roger.Bivand@nhh.no>, 
John Verzani <verzani@math.csi.cuny.edu>, 
Olivia Lau <olivia.lau@post.harvard.edu>, 
NM <nsmatloff@ucdavis.edu>, 
DC <dicook.rj@gmail.com>, 
MK <kaneplusplus@gmail.com>
```

**Comment by csgillespie** [comment]
Where should the editors file be kept?

**Comment by mitchelloharawild** [comment]
I've currently set it to the root of the current working directory, which as far as I know should be the articles repository when using the rj package. Let me know if there is a more appropriate place for this.

**Comment by csgillespie** [comment]
1. So it should be at https://github.com/rjournal/articles ?
2. It feels like editors.txt should really be a CSV file, with username, email address columns

**Comment by mitchelloharawild** [comment]
1. Yes.
1. Sounds reasonable, I'll make this change.

**Comment by csgillespie** [comment]
@mitchelloharawild You should probably add Catherine and I to the list as well.

**Comment by mitchelloharawild** [comment]
Thanks. Updated file contents:

> `editors.csv`
```
name,email
Hadley Wickham,h.wickham@gmail.com
Heather Turner,ht@heatherturner.net
Martyn Plummer,Martyn.Plummer@r-project.org
Deepayan Sarkar,deepayan.sarkar@r-project.org
Bettina Grün,Bettina.Gruen@jku.at
Michael Lawrence,lawrence.michael@gene.com
Roger Bivand,Roger.Bivand@nhh.no
John Verzani,verzani@math.csi.cuny.edu
Olivia Lau,olivia.lau@post.harvard.edu
NM,nsmatloff@ucdavis.edu
DC,dicook.rj@gmail.com
MK,kaneplusplus@gmail.com,
CH,Catherine.Hurley@mu.ie,
CG,csgillespie@gmail.com
```

**Comment by csgillespie** [comment]
1. A couple of your lines have "," at the end
2. Do we need to escape the email addresses later one with "<" .. ">"?

**Comment by mitchelloharawild** [comment]
1. Thanks, fixed. I ought to get some sleep instead of working on detail oriented things.
1. Not sure if I understand your question here, but I don't think escaping emails would be necessary for the csv.

**Comment by csgillespie** [comment]
For the meantime, I moved editors.csv to inst/ in `rj`. Makes finding the file a little easier.

**Pull request merged**
